export enum Event {
    SUCCESSFUL_TACKLE = 'SUCCESSFUL_TACKLE',
    MOVEMENT_PHASE = 'MOVEMENT_PHASE',
    STANDARD_PASS = 'STANDARD_PASS',
    FIRST_TIME_PASS = 'FIRST_TIME_PASS',
    HIGH_PASS = "HIGH_PASS",
    LONG_BALL = "LONG_BALL",
    HEADER = "HEADER",
    ANY_OTHER_SCENARIO = "ANY_OTHER_SCENARIO"
}